#!/usr/bin/env python3
"""Generate docs/CONTRAST_AUDIT.md from the tokens as they stand in Theme.swift.

Reads the Day values straight out of Maude/Theme.swift so the document cannot drift
from the code it describes. Each token carries its OWN threshold, because the right
threshold depends on how the token is used, not on which table it sits in: 4.5:1 for
anything that renders as body-size words (WCAG 1.4.3), 3:1 for anything that renders
as a mark, fill, stroke or large label (1.4.11).

    python3 scripts/contrast_audit.py > docs/CONTRAST_AUDIT.md
"""
import io, re, sys


def lin(c):
    c /= 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def lum(h):
    return 0.2126 * lin((h >> 16) & 255) + 0.7152 * lin((h >> 8) & 255) + 0.0722 * lin(h & 255)


def ratio(a, b):
    la, lb = lum(a), lum(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


SRC = io.open("Maude/Theme.swift", encoding="utf-8").read()


def tok(name):
    m = re.search(r"static let %s\s*=\s*Color\.dyn\(0x([0-9A-Fa-f]{6}),\s*0x([0-9A-Fa-f]{6})" % name, SRC)
    if not m:
        sys.exit("token not found in Theme.swift: " + name)
    return int(m.group(1), 16), int(m.group(2), 16)


LIGHT = [("canvas", 0xFAFAF8), ("card", 0xFFFFFF), ("surface", 0xF3F2EF)]
DARK = [("canvas", 0x161B22), ("card", 0x21262D), ("surface", 0x1B2028)]
OLD_GROUND = 0xE9F1FA

# (token, threshold, how it is used — the reason for that threshold)
CLINICAL = [
    ("tirVeryLow",   3.0, "band fill + hatch"),
    ("tirLow",       3.0, "band fill"),
    ("tirTarget",    3.0, "band fill, swatch, dot — FILL ONLY since 2026-09-07"),
    ("tirTargetText", 4.5, "the words: axis target edges, in-range label, TIR headline"),
    ("tirHigh",      3.0, "band fill"),
    ("tirVeryHigh",  3.0, "band fill + dots"),
    ("clinRed",      3.0, "chart mark, always paired with a word"),
    ("devMed",       3.0, "heatmap cell fill"),
    ("devHigh",      3.0, "heatmap cell fill"),
    ("devOutlier",   3.0, "heatmap cell fill + ring"),
]
DOMAIN = [
    ("accentSleep",    3.0, "line stroke, dots"),
    ("accentGlucose",  3.0, "line stroke, dots"),
    ("accentRecovery", 3.0, "line stroke, labelled squares"),
    ("accentHeart",    3.0, "line stroke, dots"),
    ("accentFinance",  3.0, "line stroke, dots"),
]
BRAND = [
    ("ink",          4.5, "body and headline text"),
    ("ink2",         4.5, "secondary text"),
    ("ink3",         4.5, "captions, kickers, inactive tabs — body size"),
    ("ink4",         3.0, "hint tier: axis labels and UI only, never body size"),
    ("moss",         4.5, "links, primary buttons, positive text"),
    ("rust",         4.5, "refusal and boundary text"),
    ("terracotta",   3.0, "kicker rail and verdict rule — declared, not yet wired"),
    ("bronze",       3.0, "marks and borders on a tan fill — declared, no call sites"),
    ("slateBlue",    4.5, "financial and context text"),
    ("infraGreen",   4.5, "system-state labels"),
    ("personalBlue", 4.5, "personal-zone labels"),
    ("amber",        3.0, "signal fill — never small text (Theme.swift rule)"),
    ("clay",         3.0, "signal fill"),
    ("brass",        4.5, "TEXT: Settings, onboarding, token wallet, study consent"),
    ("fjordBright",  3.0, "graphic only (Theme.swift rule)"),
]


def table(rows, out, dark=False):
    grounds = DARK if dark else LIGHT
    out.append("| token | hex | canvas | card | surface | needs | verdict | used as |")
    out.append("|---|---|---:|---:|---:|---:|---|---|")
    worst_fail = []
    for name, need, use in rows:
        l, d = tok(name)
        v = d if dark else l
        rs = [ratio(v, g) for _, g in grounds]
        ok = min(rs) >= need
        if not ok:
            worst_fail.append((name, min(rs), need))
        out.append("| `%s` | `#%06X` | %.2f | %.2f | %.2f | %.1f | %s | %s |"
                   % (name, v, rs[0], rs[1], rs[2], need, "pass" if ok else "**below**", use))
    out.append("")
    return worst_fail


o = []
A = o.append
A("# Contrast audit — PPCN v3 grounds")
A("")
A("Generated by `scripts/contrast_audit.py` from `Maude/Theme.swift`. WCAG 2.2 relative")
A("luminance, sRGB. Each token carries its own threshold, because the right threshold")
A("depends on how the token is used: **4.5:1** where it renders as body-size words")
A("(1.4.3), **3:1** where it renders as a mark, fill or stroke (1.4.11).")
A("")
A("Grounds — Day: canvas `#FAFAF8` · card `#FFFFFF` · surface `#F3F2EF`.")
A("Night: `#161B22` · `#21262D` · `#1B2028`.")
A("")
A("## The headline: the ground move cost nothing")
A("")
A("The canvas went from A7.2's cool `#E9F1FA` (relative luminance %.3f) to PPCN's warm"
  % lum(OLD_GROUND))
A("`#FAFAF8` (%.3f). **Lighter, not darker.** Contrast is a ratio against the ground, so"
  % lum(0xFAFAF8))
A("every token in the file gained and none lost — the smallest gain was +0.10, and `brass`,")
A("which renders as text, crossed 4.36 -> 4.75 on the canvas, i.e. from failing AA to passing")
A("it. The rebrand introduced no contrast regression anywhere, in either mode. Everything")
A("flagged below is inherited from A7.2 and was already true before the theme was touched.")
A("")
A("## Day")
A("")
A("### Clinical layer — frozen by `qms/RISK.md`, do not repaint")
A("")
clin_fail = table(CLINICAL, o)
A("The fills that sit under 3:1 against the ground — `tirTarget`, `tirHigh`, `devMed`,")
A("`devHigh`, `devOutlier` — are defensible as fills. They are large regions read against")
A("each other rather than against the paper, and each carries its own word, so meaning")
A("survives without the ground contrast doing any work.")
A("")
A("### The glucose legibility fix — decided and applied 2026-09-07")
A("")
A("Two defects were found here, both inherited, and both are now fixed. The ramp itself did")
A("not move: `tirTarget` is unchanged and is still the fill everywhere it is a band, a")
A("swatch or a dot. What changed is what happens when a clinical colour renders **words**.")
A("")
A("**1. `tirTarget` was used as text.** Clinical green is 2.05:1 on white, against a 4.5:1")
A("requirement, at these sites:")
A("")
A("- `OuraComponents.swift:198,200` and `GlucoseDetailView.swift:570,572` — the target-edge")
A("  figures on the y-axis, 9pt mono")
A("- `OuraComponents.swift:248` and `GlucoseDetailView.swift:604` — the in-range band label")
A("- `_GlassLab.swift:135` — the TIR headline percentage, 16pt mono")
A("")
A("The time-in-range percentage is the most important number on the glucose screen and it")
A("was the least legible thing on it.")
A("")
A("Fixed by adding `tirTargetText` `#007D3D` — same hue (149.1°), same full saturation,")
A("lightness 0.40 to 0.246 — used ONLY where the token renders words. It reads as the same")
A("green and clears AA on every ground including the target band\'s own 12% wash, which is")
A("what the in-range label actually sits on. Night needs no sibling and is untouched.")
A("`GlucoseDetailView` had one property serving both roles; it is now `inBandColor` for")
A("fills and `inBandText` for words.")
A("")
A("**2. The five band labels were text on a 12% wash of themselves.** `ClinicalTIRZones`")
A("drew VERY LOW / LOW / IN RANGE / HIGH / VERY HIGH in each band\'s own colour, over that")
A("colour at 12% opacity: measured 1.44:1 for HIGH, 1.85:1 for IN RANGE, 2.93:1 for LOW.")
A("")
A("These labels ARE the never-colour-alone mechanism (PR-105). A label nobody can read is")
A("not a redundant channel, it is a decoration, so the guarantee was not being met. The")
A("words now render in `ink` — 14.5:1 to 17.2:1 on every band — and the colour channel is")
A("untouched: the fill and the hatch and dot patterns still carry it at full strength. This")
A("follows the `clayText` precedent, which solves the identical problem for amber.")
A("")
A("### Per-domain data colours")
A("")
table(DOMAIN, o)
A("`accentGlucose` (2.93) and `accentRecovery` (2.80) land just under 3:1 on the canvas.")
A("Both are line strokes and dots with an axis label beside them, and Theme.swift already")
A("notes that `accentRecovery`'s solid squares need labels. Recorded, not changed: moving")
A("a per-domain colour is a design decision, not a defect fix.")
A("")
A("### Brand layer")
A("")
brand_fail = table(BRAND, o)
A("Three tokens moved, and only three. `ink3` and `ink4` were carried over from A7.2 with")
A("inline claims of 4.6:1 and >=3:1; measured, they gave 4.37 and 2.85, so both claims were")
A("false. `brass` is used as text in four screens and gave 4.44 on `surface`. Each was")
A("darkened one step at unchanged hue and saturation until its claim became true. The largest")
A("shift is 0.03 in lightness — not a visible change, just an honest one. The table above is")
A("the corrected state.")
A("")
if brand_fail:
    A("Still short, and left alone deliberately:")
    A("")
    WHY = {
        "amber": "the signal amber. Theme.swift already forbids it as small text on a light "
                 "ground; every call site is a fill or a stroke with a word beside it.",
        "clay": "the same hex as `amber`, same rule, same call-site shape.",
        "fjordBright": "PPCN tan, deliberately low-contrast and marked graphic-only in "
                       "Theme.swift. Solid squares in it require an adjacent label, which the "
                       "call sites have.",
    }
    for n, v, need in brand_fail:
        A("- `%s` — %.2f against %.1f: %s" % (n, v, need, WHY.get(n, "no note recorded.")))
    A("")
A("## Night")
A("")
A("Night clears every threshold on every ground. Tabulated for completeness.")
A("")
table(CLINICAL, o, dark=True)
table(DOMAIN, o, dark=True)
table(BRAND, o, dark=True)
A("## Re-running this")
A("")
A("```")
A("python3 scripts/contrast_audit.py > docs/CONTRAST_AUDIT.md")
A("```")
A("")
A("It reads the live values out of `Maude/Theme.swift`, so it cannot fall out of step with")
A("the code. Run it after any colour change and commit the result alongside.")

print("\n".join(o))
